<?php

declare(strict_types=1);

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Queue;
use Modules\Ai\Jobs\ProcessAiGenerationJob;
use Modules\Auth\Models\User;
use Modules\Forms\Agents\FormSchemaGenerator;
use Tests\TestCase;

uses(TestCase::class, RefreshDatabase::class);

test('it queues an ai form schema generation job via API endpoint', function (): void {
    Queue::fake();

    $user = User::factory()->create();

    $response = $this->actingAs($user, 'sanctum')->postJson('/api/forms/generate-form', [
        'prompt' => 'Create a customer feedback survey form with rating and comments',
        'async' => true,
    ]);

    $response->assertStatus(202);
    $response->assertJsonStructure([
        'message',
        'job' => ['id', 'user_id', 'type', 'prompt', 'status'],
    ]);

    Queue::assertPushed(ProcessAiGenerationJob::class);
});

test('it generates an ai form schema synchronously when async is false', function (): void {
    FormSchemaGenerator::fake([
        'form_title' => 'Faked Form',
        'description' => 'A form generated by fake agent',
        'submit_button_text' => 'Submit',
        'fields' => [],
    ]);

    $user = User::factory()->create();

    $response = $this->actingAs($user, 'sanctum')->postJson('/api/forms/generate-form', [
        'prompt' => 'Create a customer feedback survey form with rating and comments',
        'async' => false,
    ]);

    $response->assertStatus(200);
    $response->assertJsonStructure([
        'form' => ['form_title', 'description', 'submit_button_text', 'fields'],
    ]);
});
