<?php

declare(strict_types=1);

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Queue;
use Modules\Ai\Jobs\ProcessAiGenerationJob;
use Modules\Auth\Models\User;
use Modules\Category\Agents\CategoryTaxonomyGenerator;
use Tests\TestCase;

uses(TestCase::class, RefreshDatabase::class);

test('it queues an ai category taxonomy generation job via API endpoint', function (): void {
    Queue::fake();

    $user = User::factory()->create();

    $response = $this->actingAs($user, 'sanctum')->postJson('/api/category/generate-taxonomy', [
        'prompt' => 'Generate category taxonomy for an e-commerce tech store',
        'async' => true,
    ]);

    $response->assertStatus(202);
    $response->assertJsonStructure([
        'message',
        'job' => ['id', 'user_id', 'type', 'prompt', 'status'],
    ]);

    Queue::assertPushed(ProcessAiGenerationJob::class);
});

test('it generates an ai category taxonomy synchronously when async is false', function (): void {
    CategoryTaxonomyGenerator::fake([
        'name' => 'Faked Category',
        'slug' => 'faked-category',
        'description' => 'A category generated by fake agent',
        'subcategories' => [],
    ]);

    $user = User::factory()->create();

    $response = $this->actingAs($user, 'sanctum')->postJson('/api/category/generate-taxonomy', [
        'prompt' => 'Generate category taxonomy for an e-commerce tech store',
        'async' => false,
    ]);

    $response->assertStatus(200);
    $response->assertJsonStructure([
        'taxonomy' => ['name', 'slug', 'description', 'subcategories'],
    ]);
});
