<?php

declare(strict_types=1);

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Queue;
use Modules\Ai\Jobs\ProcessAiGenerationJob;
use Modules\Auth\Models\User;
use Modules\Workflow\Agents\WorkflowGenerator;
use Tests\TestCase;

uses(TestCase::class, RefreshDatabase::class);

test('it queues an ai workflow generation job via API endpoint', function (): void {
    Queue::fake();

    $user = User::factory()->create();

    $response = $this->actingAs($user, 'sanctum')->postJson('/api/workflow/generate-workflow', [
        'prompt' => 'Create a user onboarding workflow with email sequence and tag update',
        'async' => true,
    ]);

    $response->assertStatus(202);
    $response->assertJsonStructure([
        'message',
        'job' => ['id', 'user_id', 'type', 'prompt', 'status'],
    ]);

    Queue::assertPushed(ProcessAiGenerationJob::class);
});

test('it generates an ai workflow synchronously when async is false', function (): void {
    WorkflowGenerator::fake([
        'name' => 'Faked Workflow',
        'description' => 'A workflow generated by fake agent',
        'trigger' => [
            'type' => 'user_registered',
            'config' => [],
        ],
        'nodes' => [],
    ]);

    $user = User::factory()->create();

    $response = $this->actingAs($user, 'sanctum')->postJson('/api/workflow/generate-workflow', [
        'prompt' => 'Create a user onboarding workflow with email sequence and tag update',
        'async' => false,
    ]);

    $response->assertStatus(200);
    $response->assertJsonStructure([
        'workflow' => ['name', 'description', 'trigger', 'nodes'],
    ]);
});
