import { InputTypes } from '@modules/Builder/resources/scripts/enums';

export const DEVICES = [
    { label: 'Desktop', value: 'desktop', icon: 'ph:desktop' },
    {
        label: 'Tablet',
        value: 'tablet',
        icon: 'ph:device-tablet-camera',
    },
    {
        label: 'Mobile',
        value: 'mobile',
        icon: 'ph:device-mobile-camera',
    },
];

export const formInputTypes = [
    { value: InputTypes.Text, label: 'Text' },
    { value: InputTypes.Textarea, label: 'Textarea' },
    { value: InputTypes.Email, label: 'Email' },
    { value: InputTypes.Number, label: 'Number' },
    { value: InputTypes.Select, label: 'Select' },
    { value: InputTypes.MultiSelect, label: 'Multi-select' },
    { value: InputTypes.Radio, label: 'Radio' },
    { value: InputTypes.Checkbox, label: 'Checkbox' },
    { value: InputTypes.CheckboxGroup, label: 'Checkbox group' },
    { value: InputTypes.Password, label: 'Password' },
    { value: InputTypes.Date, label: 'Date' },
    // { value: InputTypes.Hidden, label: 'Hidden' }
];

export const fontWeights = [
    { value: 100, label: 'Thin' },
    { value: 200, label: 'Extra-light' },
    { value: 300, label: 'Light' },
    { value: 400, label: 'Normal' },
    { value: 500, label: 'Medium' },
    { value: 600, label: 'Semi-bold' },
    { value: 700, label: 'Bold' },
    { value: 800, label: 'Extra-bold' },
    { value: 900, label: 'Thick' },
];

export const textTransforms = [
    { value: 'none', label: 'None' },
    { value: 'capitalize', label: 'Capitalize' },
    { value: 'lowercase', label: 'Lowercase' },
    { value: 'uppercase', label: 'Uppercase' },
];

export const gridLayout = [
    { label: 'Start', value: 'start', icon: 'ph:align-left-fill' },
    {
        label: 'Center',
        value: 'center',
        icon: 'ph:align-center-horizontal-fill',
    },
    { label: 'End', value: 'end', icon: 'ph:align-right-fill' },
    {
        label: 'Stretch',
        value: 'stretch',
        icon: 'lucide:align-horizontal-space-between',
    },
];

export const FONTS = [
    'Abel',
    'Abril Fatface',
    'Acme',
    'Advent Pro',
    'Alex Brush',
    'Alfa Slab One',
    'Almarai',
    'Allura',
    'Anton',
    'Archivo Narrow',
    'Assistant',
    'Barlow',
    'Barlow Condensed',
    'Barlow Semi Condensed',
    'Bebas Neue',
    'Big Shoulders',
    'Big Shoulders Inline',
    'Big Shoulders Stencil',
    'Bitter',
    'Bree Serif',
    'Cairo',
    'Cairo Play',
    'Catamaran',
    'Caveat',
    'Caveat Brush',
    'Cedarville',
    'Chakra Petch',
    'Cinzel',
    'Cinzel Decorative',
    'Comfortaa',
    'Cookie',
    'Dancing Script',
    'DM Sans',
    'DM Serif Display',
    'DM Serif Text',
    'Domine',
    'Dosis',
    'Exo',
    'Figtree',
    'Fira Sans',
    'Fira Sans Condensed',
    'Fira Sans Extra Condensed',
    'Fjalla One',
    'Frank Ruhl Libre',
    'Great Vibes',
    'Heebo',
    'Hind',
    'Hind Siliguri',
    'IBM Plex Sans',
    'IBM Plex Sans Condensed',
    'Inconsolata',
    'Indie Flower',
    'Inter',
    'Inter Tight',
    'Josefin Sans',
    'Jost',
    'Kanit',
    'Karla',
    'Kaushan Script',
    'Lato',
    'Libre Baskerville',
    'Libre Franklin',
    'Lilita One',
    'Lobster',
    'Lobster Two',
    'Lora',
    'Manrope',
    'Marcellus',
    'Merienda',
    'Merriweather',
    'Merriweather Sans',
    'Mukta',
    'Mulish',
    'Nanum Gothic',
    'Nanum Myeongjo',
    'Noto Sans JP',
    'Noto Serif',
    'Noto Serif JP',
    'Nunito',
    'Nunito Sans',
    'Open Sans',
    'Oleo Script',
    'Orbitron',
    'Oswald',
    'Outfit',
    'Oxygen',
    'Pacifico',
    'Parisienne',
    'Passion One',
    'Patrick Hand',
    'Patrick Hand SC',
    'Permanent Marker',
    'Play',
    'Playfair Display',
    'Poppins',
    'Prompt',
    'PT Sans',
    'PT Sans Caption',
    'PT Sans Narrow',
    'PT Serif',
    'Questrial',
    'Quicksand',
    'Rajdhani',
    'Raleway',
    'Recursive',
    'Righteous',
    'Roboto',
    'Roboto Condensed',
    'Roboto Flex',
    'Roboto Mono',
    'Roboto Serif',
    'Roboto Slab',
    'Tangerine',
];

export const AOS_ANIMATIONS = [
    { value: 'none', label: 'None' },
    {
        value: 'fading-entrances',
        label: '--Fade animations',
        type: 'label',
    },
    { value: 'fade', label: 'Fade' },
    { value: 'fade-up', label: 'Fade up' },
    { value: 'fade-down', label: 'Fade down' },
    { value: 'fade-left', label: 'Fade left' },
    { value: 'fade-right', label: 'Fade right' },
    { value: 'fade-up-right', label: 'Fade up right' },
    { value: 'fade-up-left', label: 'Fade up left' },
    { value: 'fade-down-right', label: 'Fade down right' },
    { value: 'fade-down-left', label: 'Fade down left' },
    {
        value: 'flip-animations',
        label: '--Flip animations',
        type: 'label',
    },
    { value: 'flip-up', label: 'Flip up' },
    { value: 'flip-down', label: 'Flip down' },
    { value: 'flip-left', label: 'Flip left' },
    { value: 'flip-right', label: 'Flip right' },
    {
        value: 'slide-animations',
        label: '--Slide animations',
        type: 'label',
    },
    { value: 'slide-up', label: 'Slide up' },
    { value: 'slide-down', label: 'Slide down' },
    { value: 'slide-left', label: 'Slide left' },
    { value: 'slide-right', label: 'Slide right' },
    {
        value: 'zoom-animations',
        label: '--Zoom animations',
        type: 'label',
    },
    { value: 'zoom-in', label: 'Zoom in' },
    { value: 'zoom-in-up', label: 'Zoom in up' },
    { value: 'zoom-in-down', label: 'Zoom in down' },
    { value: 'zoom-in-left', label: 'Zoom in left' },
    { value: 'zoom-in-right', label: 'Zoom in right' },
    { value: 'zoom-out', label: 'Zoom in' },
    { value: 'zoom-out-up', label: 'Zoom out up' },
    { value: 'zoom-out-down', label: 'Zoom out down' },
    { value: 'zoom-out-left', label: 'Zoom out left' },
    { value: 'zoom-out-right', label: 'Zoom out right' },
];

export const ANIMATIONS = [
    { value: 'none', label: 'None' },
    {
        value: 'fading-entrances',
        label: '--Fading Entrances animations',
        type: 'label',
    },
    { value: 'fadeIn', label: 'fadeIn' },
    { value: 'fadeInDown', label: 'fadeInDown' },
    { value: 'fadeInDownBig', label: 'fadeInDownBig' },
    { value: 'fadeInLeft', label: 'fadeInLeft' },
    { value: 'fadeInLeftBig', label: 'fadeInLeftBig' },
    { value: 'fadeInRight', label: 'fadeInRight' },
    { value: 'fadeInRightBig', label: 'fadeInRightBig' },
    { value: 'fadeInUp', label: 'fadeInUp' },
    { value: 'fadeInUpBig', label: 'fadeInUpBig' },
    { value: 'fadeInTopLeft', label: 'fadeInTopLeft' },
    { value: 'fadeInTopRight', label: 'fadeInTopRight' },
    { value: 'fadeInBottomLeft', label: 'fadeInBottomLeft' },
    { value: 'fadeInBottomRight', label: 'fadeInBottomRight' },
    {
        value: 'attention-seekers',
        label: '--Attention Seekers animations',
        type: 'label',
    },
    { value: 'bounce', label: 'bounce' },
    { value: 'flash', label: 'flash' },
    { value: 'pulse', label: 'pulse' },
    { value: 'rubberBand', label: 'rubberBand' },
    { value: 'shakeX', label: 'shakeX' },
    { value: 'shakeY', label: 'shakeY' },
    { value: 'headShake', label: 'headShake' },
    { value: 'swing', label: 'swing' },
    { value: 'tada', label: 'tada' },
    { value: 'wobble', label: 'wobble' },
    { value: 'jello', label: 'jello' },
    { value: 'heartBeat', label: 'heartBeat' },
    {
        value: 'back-entrances',
        label: '--Back Entrances animations',
        type: 'label',
    },
    { value: 'backInDown', label: 'backInDown' },
    { value: 'backInLeft', label: 'backInLeft' },
    { value: 'backInRight', label: 'backInRight' },
    { value: 'backInUp', label: 'backInUp' },
    { value: 'back-exits', label: '--Back Exits animations', type: 'label' },
    { value: 'backOutDown', label: 'backOutDown' },
    { value: 'backOutLeft', label: 'backOutLeft' },
    { value: 'backOutRight', label: 'backOutRight' },
    { value: 'backOutUp', label: 'backOutUp' },
    {
        value: 'bouncing-entrances',
        label: '--Bouncing Entrances animations',
        type: 'label',
    },
    { value: 'bounceIn', label: 'bounceIn' },
    { value: 'bounceInDown', label: 'bounceInDown' },
    { value: 'bounceInLeft', label: 'bounceInLeft' },
    { value: 'bounceInRight', label: 'bounceInRight' },
    { value: 'bounceInUp', label: 'bounceInUp' },
    {
        value: 'rotating-entrances',
        label: '--Rotating Entrances animations',
        type: 'label',
    },
    { value: 'rotateIn', label: 'rotateIn' },
    { value: 'rotateInDownLeft', label: 'rotateInDownLeft' },
    { value: 'rotateInDownRight', label: 'rotateInDownRight' },
    { value: 'rotateInUpLeft', label: 'rotateInUpLeft' },
    { value: 'rotateInUpRight', label: 'rotateInUpRight' },
    {
        value: 'zooming-entrances',
        label: '--Zooming Entrances animations',
        type: 'label',
    },
    { value: 'zoomIn', label: 'zoomIn' },
    { value: 'zoomInDown', label: 'zoomInDown' },
    { value: 'zoomInLeft', label: 'zoomInLeft' },
    { value: 'zoomInRight', label: 'zoomInRight' },
    { value: 'zoomInUp', label: 'zoomInUp' },
    {
        value: 'sliding-entrances',
        label: '--Sliding Entrances animations',
        type: 'label',
    },
    { value: 'slideInDown', label: 'slideInDown' },
    { value: 'slideInLeft', label: 'slideInLeft' },
    { value: 'slideInRight', label: 'slideInRight' },
    { value: 'slideInUp', label: 'slideInUp' },
];
