<?php

declare(strict_types=1);

namespace Modules\Forms\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Modules\Ai\Services\AiGenerationService;
use Modules\Forms\Agents\FormSchemaGenerator;
use Modules\Forms\Models\Form;
use PromptPHP\Intercept\Exceptions\InterceptException;
use PromptPHP\Intercept\InjectionGuard\Exceptions\PromptInjectionGuardException;

class AiFormController extends Controller
{
    public function __construct(protected AiGenerationService $aiService) {}

    public function __invoke(Request $request): JsonResponse
    {
        $request->validate([
            'prompt' => ['required', 'string', 'max:2000'],
            'async' => ['nullable', 'boolean'],
        ]);

        // Support async queued mode by default unless explicitly disabled with async=false
        if ($request->boolean('async', false)) {
            $job = $this->aiService->dispatchJob(
                prompt: $request->input('prompt'),
                type: 'form',
                userId: $request->user()?->id
            );

            return response()->json([
                'message' => 'AI form schema generation queued successfully.',
                'job' => $job,
            ], 202);
        }

        try {
            $formSchemaGenerator = new FormSchemaGenerator;
            $response = $formSchemaGenerator->prompt($request->input('prompt'));

            if (! empty($response['form_title']) || ! empty($response['title']) || ! empty($response['name'])) {
                $title = $response['form_title'] ?? $response['title'] ?? $response['name'] ?? 'AI Form';
                Form::create([
                    'name' => $title,
                    'slug' => Str::slug($title.'-'.time()),
                    'description' => $response['description'] ?? 'Generated by AI assistant.',
                    'schema' => $response['fields'] ?? $response['schema'] ?? [],
                    'is_active' => true,
                    'success_message' => 'Thank you for submitting the form.',
                ]);
            }

            return response()->json([
                'form' => $response,
            ]);
        } catch (PromptInjectionGuardException|InterceptException) {
            return response()->json([
                'message' => 'Your request could not be processed because it appears to contain unsafe prompt instructions.',
            ], 422);
        }
    }
}
